language: node_js
node_js:
  - "7"

branches:
  only:
    - master
    - /^feature.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  slack: youtyuk:kGh44GvJ7g3O3nmWWdq4eSMG
  email: false